### ISSUE TITLE
게시물만 있을 때 게시물 텍스트 위에 마진 줄이기

### ISSUE THREAD

**Issue by yunheur** [0mad/yolobook#113]
- 게시물만 있을 때 게시물 텍스트 위에 마진 줄이기

**Comment by tmmoond8** [comment]
<img width="335" alt="스크린샷 2019-06-23 오후 5 39 28" src="https://user-images.githubusercontent.com/11402468/59973718-51d98900-95de-11e9-873c-057800ead138.png">

**Comment by yunheur** [comment]
다른 이슈에서 처리할 예정이므로 닫습니다.
