### ISSUE TITLE
a 태그로 다른 페이지 이동시 페이지 렌더링이 재대로 안되는 문제 해결

### ISSUE THREAD

**Issue by yunheur** [0mad/yolobook#63]
- a 태그로 다른 페이지 이동시 페이지 렌더링이 재대로 안되는 문제 해결

**Comment by tmmoond8** [comment]
github에 정리된 내용
[](https://github.com/zeit/next-plugins/issues/282)

css를 가져오는데  /_next/static/css/styles.chunk.css 경로에서 가져오는데, 페이지가 바뀌면서 css도 계속 바뀌는데 반해 이름이 동일 하기 때문에 브라우저가 캐시하는 것으로 보임.
<link href="/_next/static/css/styles.chunk.css?v={timestamp}"/> 
이런식으로 인자를 넣어서 항상 가져오도록 수정.

이 이슈를 해결 하는 방법 두 가지를 언급했는데, 
`Router.events.on('routeChangeComplete' () => void)` 이벤트를 사용하는 방식은 시간차 때문에 css가 순간적으로 깨지길래 위 방법으로 해결했다.

**Comment by yunheur** [comment]
리뷰 완료했습니다.
