### ISSUE TITLE
프로필 사진이 없는 계정일 경우 기본 이미지가 설정되도록 처리

### ISSUE THREAD

**Issue by yunheur** [0mad/yolobook#89]
프로필 사진이 없는 계정일 경우 기본 이미지가 설정되도록 처리

- [ ]

**Comment by tmmoond8** [comment]
이 이슈는 로그인 할 때 처리해주면 좋을 것 같아서 제가 처리할 수 있을 것 같습니다.

**Comment by yunheur** [comment]
해결되었으므로 이슈를 닫습니다.
